// Package swagger GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "taekyu.kang@sk.com",
            "email": "taekyu.kang@sk.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/app-groups": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get appGroup list by giving params",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AppGroups"
                ],
                "summary": "Get appGroup list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "clusterId",
                        "name": "clusterId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetAppGroupsResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Install appGroup",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AppGroups"
                ],
                "summary": "Install appGroup",
                "parameters": [
                    {
                        "description": "create appgroup request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateAppGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.CreateAppGroupResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Uninstall appGroup",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AppGroups"
                ],
                "summary": "Uninstall appGroup",
                "parameters": [
                    {
                        "description": "body",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/app-groups/{appGroupId}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get appGroup detail by appGroupId",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AppGroups"
                ],
                "summary": "Get appGroup detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "appGroupId",
                        "name": "appGroupId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetAppGroupResponse"
                        }
                    }
                }
            }
        },
        "/app-groups/{appGroupId}/applications": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get applications",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AppGroups"
                ],
                "summary": "Get applications",
                "parameters": [
                    {
                        "type": "string",
                        "description": "appGroupId",
                        "name": "appGroupId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "applicationType",
                        "name": "applicationType",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetApplicationsResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Update application",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AppGroups"
                ],
                "summary": "Update application",
                "parameters": [
                    {
                        "description": "body",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateApplicationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/app-serve-apps": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get appServeApp list by giving params",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AppServeApps"
                ],
                "summary": "Get appServeApp list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "project_id",
                        "name": "projectId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "show_all",
                        "name": "showAll",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.AppServeApp"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Update appServeApp",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AppServeApps"
                ],
                "summary": "Update appServeApp",
                "parameters": [
                    {
                        "description": "body",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Install appServeApp",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AppServeApps"
                ],
                "summary": "Install appServeApp",
                "parameters": [
                    {
                        "description": "body",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Uninstall appServeApp",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AppServeApps"
                ],
                "summary": "Uninstall appServeApp",
                "parameters": [
                    {
                        "description": "body",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/app-serve-apps/{appServeAppId}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get appServeApp by giving params",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AppServeApps"
                ],
                "summary": "Get appServeApp",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AppServeApp"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "login",
                "parameters": [
                    {
                        "description": "account info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "user detail",
                        "schema": {
                            "$ref": "#/definitions/domain.LoginResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "logout",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/cloud-settings": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get CloudSettings",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CloudSettings"
                ],
                "summary": "Get CloudSettings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "show all organizations",
                        "name": "all",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetCloudSettingsResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Create CloudSetting",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CloudSettings"
                ],
                "summary": "Create CloudSetting",
                "parameters": [
                    {
                        "description": "create cloud setting request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateCloudSettingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.CreateCloudSettingResponse"
                        }
                    }
                }
            }
        },
        "/cloud-settings/{cloudSettingId}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get CloudSetting",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CloudSettings"
                ],
                "summary": "Get CloudSetting",
                "parameters": [
                    {
                        "type": "string",
                        "description": "cloudSettingId",
                        "name": "cloudSettingId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetCloudSettingResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Update CloudSetting",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CloudSettings"
                ],
                "summary": "Update CloudSetting",
                "parameters": [
                    {
                        "description": "Update cloud setting request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateCloudSettingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Delete CloudSetting",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CloudSettings"
                ],
                "summary": "Delete CloudSetting",
                "parameters": [
                    {
                        "description": "Delete cloud setting request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.DeleteCloudSettingRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "cloudSettingId",
                        "name": "cloudSettingId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/clusters": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get cluster list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clusters"
                ],
                "summary": "Get clusters",
                "parameters": [
                    {
                        "type": "string",
                        "description": "organizationId",
                        "name": "organizationId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetClustersResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Create cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clusters"
                ],
                "summary": "Create cluster",
                "parameters": [
                    {
                        "description": "create cluster request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateClusterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.CreateClusterResponse"
                        }
                    }
                }
            }
        },
        "/clusters/{clusterId}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get cluster detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clusters"
                ],
                "summary": "Get cluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "clusterId",
                        "name": "clusterId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Cluster"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Delete cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clusters"
                ],
                "summary": "Delete cluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "clusterId",
                        "name": "clusterId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Cluster"
                        }
                    }
                }
            }
        },
        "/histories": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get histories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Histories"
                ],
                "summary": "Get histories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.History"
                        }
                    }
                }
            }
        },
        "/organizations": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get organization list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organizations"
                ],
                "summary": "Get organization list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.ListOrganizationBody"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Create organization",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organizations"
                ],
                "summary": "Create organization",
                "parameters": [
                    {
                        "description": "create organization request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateOrganizationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/organizations/{organizationId}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get organization detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organizations"
                ],
                "summary": "Get organization detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "organizationId",
                        "name": "organizationId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetOrganizationResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Update organization detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organizations"
                ],
                "summary": "Update organization detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "organizationId",
                        "name": "organizationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "update organization request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateOrganizationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateOrganizationResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Delete organization",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organizations"
                ],
                "summary": "Delete organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "organizationId",
                        "name": "organizationId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Organization"
                        }
                    }
                }
            }
        },
        "/organizations/{organizationId}/primary-cluster": {
            "patch": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Update primary cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organizations"
                ],
                "summary": "Update primary cluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "organizationId",
                        "name": "organizationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "update primary cluster request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdatePrimaryClusterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/stack-templates": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get StackTemplates",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StackTemplates"
                ],
                "summary": "Get StackTemplates",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetStackTemplatesResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Create StackTemplate",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StackTemplates"
                ],
                "summary": "Create StackTemplate 'NOT IMPLEMENTED'",
                "parameters": [
                    {
                        "description": "create stack template request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateStackTemplateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.CreateStackTemplateResponse"
                        }
                    }
                }
            }
        },
        "/stack-templates/{stackTemplateId}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get StackTemplate",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StackTemplates"
                ],
                "summary": "Get StackTemplate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "stackTemplateId",
                        "name": "stackTemplateId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetStackTemplateResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Update StackTemplate",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StackTemplates"
                ],
                "summary": "Update StackTemplate 'NOT IMPLEMENTED'",
                "parameters": [
                    {
                        "description": "Update stack template request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateStackTemplateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Delete StackTemplate",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StackTemplates"
                ],
                "summary": "Delete StackTemplate 'NOT IMPLEMENTED'",
                "parameters": [
                    {
                        "type": "string",
                        "description": "stackTemplateId",
                        "name": "stackTemplateId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get user list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.ListUserBody"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Create user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "create user request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "create user response",
                        "schema": {
                            "$ref": "#/definitions/domain.CreateUserResponse"
                        }
                    }
                }
            }
        },
        "/users/{userId}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Get user detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "userId",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetUserResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Update user detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update user detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "userId",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "update user request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateUserResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Update user password detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update user password detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "userId",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "409": {
                        "description": "Conflict"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Delete user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "userId",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.User"
                        }
                    }
                }
            }
        },
        "/users/{userId}/password": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Update user password detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update user password detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "userId",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "update user password request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdatePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.UpdatePasswordResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AppGroupResponse": {
            "type": "object",
            "properties": {
                "appGroupType": {
                    "type": "integer"
                },
                "clusterId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "creator": {
                    "$ref": "#/definitions/domain.SimpleUserResponse"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "statusDescription": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updator": {
                    "$ref": "#/definitions/domain.SimpleUserResponse"
                },
                "workflowId": {
                    "type": "string"
                }
            }
        },
        "domain.AppServeApp": {
            "type": "object",
            "properties": {
                "app_type": {
                    "description": "app_type (spring/springboot)",
                    "type": "string"
                },
                "contract_id": {
                    "description": "contract_id is a contract ID which this app belongs to",
                    "type": "string"
                },
                "createdAt": {
                    "description": "created_at is a creatioin timestamp for the application",
                    "type": "string"
                },
                "endpoint_url": {
                    "description": "endpoint URL of deployed app",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "description": "application name",
                    "type": "string"
                },
                "preview_endpoint_url": {
                    "description": "preview svc endpoint URL in B/G deployment",
                    "type": "string"
                },
                "status": {
                    "description": "status is status of deployed app",
                    "type": "string"
                },
                "target_cluster_id": {
                    "description": "target cluster to which the app is deployed",
                    "type": "string"
                },
                "type": {
                    "description": "type (build/deploy/all)",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "domain.ApplicationResponse": {
            "type": "object",
            "properties": {
                "appGroupId": {
                    "type": "string"
                },
                "applicationType": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "endpoint": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "domain.CloudSetting": {
            "type": "object",
            "properties": {
                "cloudService": {
                    "type": "string"
                },
                "clusters": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "creator": {
                    "$ref": "#/definitions/domain.User"
                },
                "creatorId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "string"
                },
                "resource": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updator": {
                    "$ref": "#/definitions/domain.User"
                },
                "updatorId": {
                    "type": "string"
                }
            }
        },
        "domain.CloudSettingResponse": {
            "type": "object",
            "properties": {
                "cloudService": {
                    "type": "string"
                },
                "clusters": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "creator": {
                    "$ref": "#/definitions/domain.SimpleUserResponse"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "string"
                },
                "resource": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updator": {
                    "$ref": "#/definitions/domain.SimpleUserResponse"
                }
            }
        },
        "domain.Cluster": {
            "type": "object",
            "properties": {
                "cloudSetting": {
                    "$ref": "#/definitions/domain.CloudSetting"
                },
                "cloudSettingId": {
                    "type": "string"
                },
                "conf": {
                    "$ref": "#/definitions/domain.ClusterConf"
                },
                "createdAt": {
                    "type": "string"
                },
                "creator": {
                    "$ref": "#/definitions/domain.User"
                },
                "creatorId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "statusDesc": {
                    "type": "string"
                },
                "templateId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updator": {
                    "$ref": "#/definitions/domain.User"
                },
                "updatorId": {
                    "type": "string"
                }
            }
        },
        "domain.ClusterConf": {
            "type": "object",
            "properties": {
                "machineReplicas": {
                    "type": "integer"
                },
                "machineType": {
                    "type": "string"
                },
                "maxSizePerAz": {
                    "type": "integer"
                },
                "minSizePerAz": {
                    "type": "integer"
                },
                "numOfAz": {
                    "type": "integer"
                },
                "region": {
                    "type": "string"
                },
                "sshKeyName": {
                    "type": "string"
                }
            }
        },
        "domain.ClusterConfResponse": {
            "type": "object",
            "properties": {
                "machineReplicas": {
                    "type": "integer"
                },
                "machineType": {
                    "type": "string"
                },
                "maxSizePerAz": {
                    "type": "integer"
                },
                "minSizePerAz": {
                    "type": "integer"
                },
                "numOfAz": {
                    "type": "integer"
                },
                "region": {
                    "type": "string"
                },
                "sshKeyName": {
                    "type": "string"
                }
            }
        },
        "domain.ClusterResponse": {
            "type": "object",
            "properties": {
                "cloudSetting": {
                    "$ref": "#/definitions/domain.CloudSettingResponse"
                },
                "conf": {
                    "$ref": "#/definitions/domain.ClusterConfResponse"
                },
                "createdAt": {
                    "type": "string"
                },
                "creator": {
                    "$ref": "#/definitions/domain.SimpleUserResponse"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "statusDesc": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "domain.CreateAppGroupRequest": {
            "type": "object",
            "required": [
                "clusterId",
                "name"
            ],
            "properties": {
                "appGroupType": {
                    "type": "string",
                    "enum": [
                        "LMA",
                        "SERVICE_MESH"
                    ]
                },
                "clusterId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.CreateAppGroupResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "domain.CreateCloudSettingRequest": {
            "type": "object",
            "required": [
                "name",
                "secretKey",
                "secretKeyId"
            ],
            "properties": {
                "cloudService": {
                    "type": "string",
                    "enum": [
                        "AWS",
                        "AZZURE",
                        "GCP"
                    ]
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "string"
                },
                "secretKey": {
                    "type": "string"
                },
                "secretKeyId": {
                    "type": "string"
                }
            }
        },
        "domain.CreateCloudSettingResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "domain.CreateClusterRequest": {
            "type": "object",
            "properties": {
                "cloudSettingId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "machineReplicas": {
                    "type": "integer"
                },
                "machineType": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "numOfAz": {
                    "type": "integer"
                },
                "organizationId": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "templateId": {
                    "type": "string"
                }
            }
        },
        "domain.CreateClusterResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "domain.CreateOrganizationRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 0
                },
                "name": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "domain.CreateStackTemplateRequest": {
            "type": "object",
            "required": [
                "name",
                "organizationId",
                "platform",
                "template",
                "version"
            ],
            "properties": {
                "cloudService": {
                    "type": "string",
                    "enum": [
                        "AWS",
                        "AZZURE",
                        "GCP"
                    ]
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "template": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "domain.CreateStackTemplateResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "domain.CreateUserRequest": {
            "type": "object",
            "required": [
                "accountId",
                "password",
                "role"
            ],
            "properties": {
                "accountId": {
                    "type": "string"
                },
                "department": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 0
                },
                "description": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 0
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 0
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "admin",
                        "user"
                    ]
                }
            }
        },
        "domain.CreateUserResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "type": "object",
                    "properties": {
                        "accountId": {
                            "type": "string"
                        },
                        "department": {
                            "type": "string"
                        },
                        "description": {
                            "type": "string"
                        },
                        "email": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "organization": {
                            "$ref": "#/definitions/domain.Organization"
                        },
                        "role": {
                            "$ref": "#/definitions/domain.Role"
                        }
                    }
                }
            }
        },
        "domain.DeleteCloudSettingRequest": {
            "type": "object",
            "required": [
                "secretKey",
                "secretKeyId"
            ],
            "properties": {
                "secretKey": {
                    "type": "string"
                },
                "secretKeyId": {
                    "type": "string"
                }
            }
        },
        "domain.GetAppGroupResponse": {
            "type": "object",
            "properties": {
                "appGroup": {
                    "$ref": "#/definitions/domain.AppGroupResponse"
                }
            }
        },
        "domain.GetAppGroupsResponse": {
            "type": "object",
            "properties": {
                "appGroups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.AppGroupResponse"
                    }
                }
            }
        },
        "domain.GetApplicationsResponse": {
            "type": "object",
            "properties": {
                "applications": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ApplicationResponse"
                    }
                }
            }
        },
        "domain.GetCloudSettingResponse": {
            "type": "object",
            "properties": {
                "cloudSetting": {
                    "$ref": "#/definitions/domain.CloudSettingResponse"
                }
            }
        },
        "domain.GetCloudSettingsResponse": {
            "type": "object",
            "properties": {
                "cloudSettings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.CloudSettingResponse"
                    }
                }
            }
        },
        "domain.GetClustersResponse": {
            "type": "object",
            "properties": {
                "clusters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ClusterResponse"
                    }
                }
            }
        },
        "domain.GetOrganizationResponse": {
            "type": "object",
            "properties": {
                "organization": {
                    "type": "object",
                    "properties": {
                        "createdAt": {
                            "type": "string"
                        },
                        "creator": {
                            "type": "string"
                        },
                        "description": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "phone": {
                            "type": "string"
                        },
                        "primaryClusterId": {
                            "type": "string"
                        },
                        "status": {
                            "type": "integer"
                        },
                        "statusDescription": {
                            "type": "string"
                        },
                        "updatedAt": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "domain.GetStackTemplateResponse": {
            "type": "object",
            "properties": {
                "stackTemplate": {
                    "$ref": "#/definitions/domain.StackTemplateResponse"
                }
            }
        },
        "domain.GetStackTemplatesResponse": {
            "type": "object",
            "properties": {
                "stackTemplates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.StackTemplateResponse"
                    }
                }
            }
        },
        "domain.GetUserResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "type": "object",
                    "properties": {
                        "accountId": {
                            "type": "string"
                        },
                        "createdAt": {
                            "type": "string"
                        },
                        "creator": {
                            "type": "string"
                        },
                        "department": {
                            "type": "string"
                        },
                        "description": {
                            "type": "string"
                        },
                        "email": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "organization": {
                            "$ref": "#/definitions/domain.Organization"
                        },
                        "role": {
                            "$ref": "#/definitions/domain.Role"
                        },
                        "updatedAt": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "domain.History": {
            "type": "object",
            "properties": {
                "accountId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "historyType": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "domain.ListOrganizationBody": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "primaryClusterId": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "domain.ListUserBody": {
            "type": "object",
            "properties": {
                "accountId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "creator": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organization": {
                    "$ref": "#/definitions/domain.Organization"
                },
                "role": {
                    "$ref": "#/definitions/domain.Role"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "domain.LoginRequest": {
            "type": "object",
            "required": [
                "accountId",
                "organizationId",
                "password"
            ],
            "properties": {
                "accountId": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "domain.LoginResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "type": "object",
                    "properties": {
                        "accountId": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "organization": {
                            "$ref": "#/definitions/domain.Organization"
                        },
                        "role": {
                            "$ref": "#/definitions/domain.Role"
                        },
                        "token": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "domain.Organization": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "creator": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "primaryClusterId": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "statusDescription": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "domain.Role": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "creator": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "domain.SimpleUserResponse": {
            "type": "object",
            "properties": {
                "accountId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.StackTemplateResponse": {
            "type": "object",
            "properties": {
                "cloudService": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "creator": {
                    "$ref": "#/definitions/domain.SimpleUserResponse"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "template": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updator": {
                    "$ref": "#/definitions/domain.SimpleUserResponse"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "domain.UpdateApplicationRequest": {
            "type": "object",
            "properties": {
                "appGroupId": {
                    "type": "string"
                },
                "applicationType": {
                    "type": "string"
                },
                "endpoint": {
                    "type": "string"
                },
                "metadata": {
                    "type": "string"
                }
            }
        },
        "domain.UpdateCloudSettingRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                }
            }
        },
        "domain.UpdateOrganizationRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 0
                },
                "phone": {
                    "type": "string"
                },
                "primaryClusterId": {
                    "type": "string"
                }
            }
        },
        "domain.UpdateOrganizationResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "domain.UpdatePasswordRequest": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "password": {
                    "type": "string"
                }
            }
        },
        "domain.UpdatePasswordResponse": {
            "type": "object"
        },
        "domain.UpdatePrimaryClusterRequest": {
            "type": "object",
            "properties": {
                "primaryClusterId": {
                    "type": "string"
                }
            }
        },
        "domain.UpdateStackTemplateRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                }
            }
        },
        "domain.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "department": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 0
                },
                "description": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 0
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 0
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "admin",
                        "user"
                    ]
                }
            }
        },
        "domain.UpdateUserResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "type": "object",
                    "properties": {
                        "accountId": {
                            "type": "string"
                        },
                        "department": {
                            "type": "string"
                        },
                        "description": {
                            "type": "string"
                        },
                        "email": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "organization": {
                            "$ref": "#/definitions/domain.Organization"
                        },
                        "role": {
                            "$ref": "#/definitions/domain.Role"
                        }
                    }
                }
            }
        },
        "domain.User": {
            "type": "object",
            "properties": {
                "accountId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "creator": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organization": {
                    "$ref": "#/definitions/domain.Organization"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/domain.Role"
                },
                "token": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "JWT": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "tks-api-dev.taco-cat.xyz:9110",
	BasePath:         "/api/1.0/",
	Schemes:          []string{},
	Title:            "tks-api service",
	Description:      "This is backend api service for tks platform",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
