name: Build Image
on:
  pull_request_target:
    branches:
      - main
      - develop
      - release

env:
  SERVICE: tks-api
  TAG: ${{github.sha}}

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.HARBOR_USERNAME}}
          password: ${{secrets.HARBOR_SECRET}}

      - name: build image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: |
            sktcloud/${{env.SERVICE}}:${{env.TAG}}
